### PR TITLE
V1.4 add testcases notecommand

### LINKED ISSUE #220: Add NoteCommand Test Cases

### PR DESCRIPTION
**Pull request by Yttruire**
Resolves #220

### CODE REVIEW

**Review by tanjiaxian99 — COMMENTED** [review]
I think can add test cases for NoteCommandParser as well

**Review by tanjiaxian99 — CHANGES_REQUESTED** [review]
I think can add a test for NoteCommandParser as well

**Comment by Yttruire** [comment]
@tanjiaxian99  Added testing for NoteCommandParser, can review again already

**Review by junwei26 — APPROVED** [review]
Test cases for note command seems fine.. LGTM

**Review by tanjiaxian99 — APPROVED** [review]
LGTM!

**Pull request merged**
